schematic:
    name: Schematic
    version: 1.4.7
database:
    general:
        name: schematic
        charset: utf8
        collation: utf8_general_ci
        engine: InnoDB
    tables:
        hello_world:
            fields:
                id:
                    type: int(11)
                    'null': false
                    unsigned: true
                    autoIncrement: true
                    index: 'PRIMARY KEY'
                name:
                    type: varchar(128)
                    'null': false
                    unsigned: false
                    autoIncrement: false
                created_date:
                    type: datetime
                    'null': false
                    unsigned: false
                    autoIncrement: false
