schematic:
    name: {{ app_title }}
    version: {{ app_version }}
database:
    general:
        name: {{ database_name }}
        charset: utf8
        collation: utf8_general_ci
        engine: InnoDB
    tables:
        {{ table_name }}:
            fields:
                id:
                    type: int(11)
                    'null': false
                    unsigned: true
                    autoIncrement: true
                    index: 'PRIMARY KEY'
                name:
                    type: varchar(128)
                    'null': false
                    unsigned: false
                    autoIncrement: false
                created_date:
                    type: datetime
                    'null': false
                    unsigned: false
                    autoIncrement: false
