schematic:
    name: Schematic
    version: 1.5.0
database:
    general:
        name: test_db
        charset: utf8
        collation: utf8_general_ci
        engine: InnoDB
    tables:
        users_settings:
            fields:
                id:
                    type: int(11)
                    'null': false
                    unsigned: true
                    autoIncrement: true
                    index: 'PRIMARY KEY'
                identifier:
                    type: enum('normal', 'system')
                    'null': true
                    default: normal
                name:
                    type: varchar(128)
                    'null': false
                    unsigned: false
                value:
                    type: varchar(128)
                    'null': false
                created_date:
                    type: datetime
                    'null': false