schematic:
    name: Schematic
    version: 1.5.0
database:
    general:
        name: coopunity
        charset: utf8
        collation: utf8_general_ci
        engine: InnoDB
    tables:
        settings:
            fields:
                id:
                    type: int(11)
                    'null': false
                    unsigned: true
                    autoIncrement: true
                    index: 'PRIMARY KEY'
                key:
                    type: 'enum(''profilePictureOriginal'',''profilePictureLarge'',''profilePictureSmall'',''bannerPicture'')'
                    'null': true
                    unsigned: false
                    autoIncrement: false
                    index: INDEX
                type:
                    type: 'enum(''user'',''community'')'
                    'null': true
                    unsigned: false
                    autoIncrement: false
