schematic:
    name: Schematic
    version: 1.5.0
database:
    general:
        name: coopunity
        charset: latin1
        collation: latin1_swedish_ci
        engine: InnoDB
    tables:
        users_settings:
            fields:
                id:
                    type: int(11)
                    'null': false
                    unsigned: true
                    autoIncrement: true
                    index: 'PRIMARY KEY'
                settings_id:
                    type: int(11)
                    'null': false
                    unsigned: true
                    autoIncrement: false
                    index: INDEX
                    foreignKey:
                        table: settings
                        field: id
                        'on':
                            delete: CASCADE
                            update: CASCADE
                users_id:
                    type: int(11)
                    'null': false
                    unsigned: true
                    autoIncrement: false
                    index: INDEX
                    foreignKey:
                        table: users
                        field: id
                        'on':
                            delete: CASCADE
                            update: CASCADE
                value:
                    type: varchar(256)
                    'null': true
                    unsigned: false
                    autoIncrement: false
